### ISSUE TITLE
any plan to add LSTM recurrent neural network?

### ISSUE THREAD

**Issue by fleapapa** [01org/daal#11]

**Comment by Vika-F** [comment]
We do have plans to extend Intel® DAAL to support LSTM recurrent neural networks.
At the same time you can try [Neon™](https://github.com/NervanaSystems/neon) that has LSTM already available.
[This tutorial](https://neon.nervanasys.com/index.html/lstm.html) helps to understand how to train LSTM with Neon™.

**Comment by fleapapa** [comment]
Thanks. Is there a C++ alternative of Neon?
