### ISSUE TITLE
class definition in daal_atomic_int.h

### ISSUE THREAD

**Issue by Ethanlm** [01org/daal#2]
in the following definition, 
template <typename dataType = int>
class DAAL_EXPORT Atomic{
xxx
};

the return type of inc() and dec() should be "dataType" instead of "int"

**Comment by Ethanlm** [comment]
And I think the following definitions of   
template\<\> class DAAL_EXPORT Atomic\<int\> {};
and 
template\<\>class DAAL_EXPORT Atomic\<size_t\> {};
are not necessary

**Comment by iburyl** [comment]
Changes added to daal_2017_update1 branch. Thank you
