### ISSUE TITLE
simple operations on Tensor from java?

### ISSUE THREAD

**Issue by amuseoffire** [01org/daal#26]
on a tensor, and what i have in mind is a homogenous float tensor, is there a way to, say, set or get a value at a given index from java?  Or to call gemm?   i haven't been able to find anything

**Comment by vepifanov** [comment]
You can change a value at a given index in Java Tensors by using getSubtensor (on the block containing this element), change it in temporary buffer and release this buffer back to Java Tensor.
Assume you have n-dimensional tensor and you need to set value to position (p_0, p_1, …, p_(n-1)). Then you can do the following:
        long fDims[] = {p[0], p[1], ..., p[n - 2]};
        FloatBuffer dataFloatSubtensor = FloatBuffer.allocate((int) 1);
        dataTensor.getSubtensor(fDims, p[n - 1], 1, dataFloatSubtensor);
        dataFloatSubtensor.put(0, value);
        dataTensor.releaseSubtensor(fDims, p[n - 1], 1, dataFloatSubtensor);

Another option: if you create homogeneous tensor on top of the Java Array, you can modify elements directly in this Array and it will be automatically passed to the tensor.
