### ISSUE TITLE
DAAL update 2017 K-MEANS Crash

### ISSUE THREAD

**Issue by vivien7806** [01org/daal#29]
libJavaApi.so sometimes crash when trying to retrieve the clusters center using HomogenousNumericTable getBlockOfColumnValues Java API.

**Comment by vepifanov** [comment]
Hi Vivien,

The numeric table with centroids consists of one row and nFeatures columns. It would be more appropriate to use getBlockOfRows method to accesss the centroids. Can you try this method and let us know if this doesn’t help?

**Comment by vivien7806** [comment]
Hi,

Thanks for your answer,
It works a lot better this way.
