### ISSUE TITLE
Extract nodes from trained Decision Tree

### ISSUE THREAD

**Issue by matthieubulte** [01org/daal#36]
Hi,

I'm trying to extract the nodes learned from a classification decision tree model in order to export them to some UI and visualize them, unfortunately it seems that there is no way to access them from the `Model` class.

Did I miss something?

If not, is there any plan to let the user access the `DecisionTreeTablePtr`, as it is already possible for other models such as the `betas` of a linear model or the `centroids` of a kmeans model?

Thanks

**Comment by Vika-F** [comment]
Current version of Intel DAAL hides the implementation of decision tree model, so you cannot visualize its contents.
However, the decision forest algorithm provides [NodeVisitor](https://github.com/01org/daal/blob/daal_2018_beta_update1/include/algorithms/decision_forest/decision_forest_regression_model.h#L64) feature that gives an ability to traverse the Model.
In the upcoming release we plan to introduce node visitor feature in decision tree algorithm as well.
This [example](https://github.com/01org/daal/blob/daal_2018_beta_update1/examples/cpp/source/decision_forest/df_cls_traverse_model.cpp) shows the usage of node visitor in decision forest algorithm.

**Comment by matthieubulte** [comment]
Thanks for your answer, looking forward to having access to the `NodeVisitor` for decision trees.
