### ISSUE TITLE
Problems in building

### ISSUE THREAD

**Issue by melrobin** [01org/daal#4]
I am trying to build DAAL, but encounter the following error
lang_service/java/com/intel/daal/algorithms/parameter.cpp:18:17: fatal error: jni.h: No such file or directory

The problem is my include path, but how would I set this in the build?  I have tried the -I option of make and it does not work.  I also tried CXXFLAGS.

**Comment by iburyl** [comment]
You can do that via setting environment variable. For Windows that will be INCLUDE variable, for Linux that will be CPATH variable.

**Comment by melrobin** [comment]
OK, thanks!  I'm using Fedora 23.  DAAL does not seem to be picking up the CPATH variable for some reason.  Do you have any other ideas?  I looked to find a jni.h within the archive and, not surprisingly, did not.

**Comment by melrobin** [comment]
OK, got past this error by modifying the CPLUS_INCLUDE_PATH environment variable.  Thank you for the inspiration.

**Comment by iburyl** [comment]
Interesting, can you please tell which compiler are you using?

**Comment by melrobin** [comment]
I think that CPATH would have worked except that the build broke on g++, so CPLUS_INCLUDE_PATH worked.

**Comment by iburyl** [comment]
According to [documentation](https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html) CPATH should work for both C/C++, while C_INCLUDE_PATH is specific for C and CPLUS_INCLUDE_PATH is specific for C++. Thus something works not exactly as expected.

**Comment by melrobin** [comment]
This is good information.  I'll definitely check into what's going on.

**Comment by stmandl** [comment]
Thanks for the hint.
I just successfully compiled the library on Ubuntu 16.04 using this command:

`make daal PLAT=lnx32e COMPILER=gnu CPATH=/usr/lib/jvm/java-8-openjdk-amd64/include:/usr/lib/jvm/java-8-openjdk-amd64/include/linux/`
