### ISSUE TITLE
External Dependencies of DAAL

### ISSUE THREAD

**Issue by vkirangoud** [01org/daal#41]
I noticed DAAL library is depended on external libraries like "libdaal_mkl_sequential.a  libdaal_mkl_thread.a  libdaal_vmlipp_core.a", what are these libraries? Can I use DAAL without these external dependencies.
I was looking at Cholesky Factorization for batch processing, I want to use DAAL framework but use different optimization kernel of Cholesky, will this be possible.

**Comment by RuslanIsrafilov** [comment]
@vkirangoud, DAAL depends on external functional like BLAS, LAPACK, mathematical functions, random number generators, sorting, data compression algorithms and so on. The libraries you mentioned contain necessary implementations. I see two options to use another implementation:
* DAAL has additional abstraction layer for external functions (for example have look at [service_lapack.h](https://github.com/01org/daal/blob/daal_2018_beta_update1/externals/service_lapack.h)), so you can push new implementation underneath of you own abstraction layer.
* Use new external libraries with the same ABI.

**Comment by RuslanIsrafilov** [comment]
> I want to use DAAL framework but use different optimization kernel of Cholesky
Do you want to use DAAL interface while having your own Cholesky implementation or you just want to replace call to LAPACK inside of existing DAAL algorithm?

**Comment by vkirangoud** [comment]
I want to have my own cholesky implementation using DAAL interface.

**Comment by RuslanIsrafilov** [comment]
[Here is guide](https://software.intel.com/en-us/articles/intel-data-analytics-acceleration-library-intel-daal-how-to-add-user-defined-algorithm) describing how to add custom algorithm to DAAL. To minimize efforts you may inherit your algorithm's class from `cholesky::Batch` and override the method `compute`.

**Comment by Vika-F** [comment]
An addition to the comment of @RuslanIsrafilov .
@vkirangoud , you will need to inherit two classes: cholesky::Batch which implements an interface of the algorithm and cholesky::BatchContainer which contains an implementation of the algorithm. And the compute() method should be overridden in the class derived from cholesky::BatchContainer.
