### ISSUE TITLE
install DAAL 2018

### ISSUE THREAD

**Issue by fleapapa** [01org/daal#42]
i tried to install DAAL 2018 but after downloading and untar-ing the zipball l_daal_2018.0.128.tgz, i found install.sh is an empty file. 

What do i do now to fix it?

**Comment by GennadyFedorov** [comment]
I don't see the problem on my side with this package. 
pls have  a look at the log:
l_daal_2018.0.128]$ ls -all
total 72
drwxr-xr-x 4 gfedorov users  4096 Aug 24 12:43 .
drwxr-xr-x 3 gfedorov users  4096 Sep 18 08:14 ..
-rwxr-xr-x 1 gfedorov users  3264 Aug 24 12:41 cd_eject.sh
-rwxr-xr-x 1 gfedorov users   180 Aug 24 12:41 install_GUI.sh
**-rwxr-xr-x 1 gfedorov users 21257 Aug 24 12:42 install.sh****
-rw-r--r-- 1 gfedorov users   418 Aug 24 11:45 ipsxe_support_daal.txt
-rw-r--r-- 1 gfedorov users 11040 Aug 14 17:19 license.txt
drwxr-xr-x 6 gfedorov users  4096 Aug 24 12:43 pset
-rw-r--r-- 1 gfedorov users   975 Aug 24 11:45 PUBLIC_KEY.PUB
drwxr-xr-x 2 gfedorov users  4096 Aug 24 12:43 rpm
-rwxr-xr-x 1 gfedorov users  1257 Aug 24 12:42 silent.cfg

**Comment by fleapapa** [comment]
I untar it again. This time the files are good. Thanks.
