### ISSUE TITLE
Build failed on gcc5.4 linux

### ISSUE THREAD

**Issue by yvdriess** [01org/daal#6]
'__work_gnu/lnx32e/kernel/service_atomic_int.o' failed to compile due to a syntax error:

__work_gnu/lnx32e/kernel/service_atomic_int.cpp:33:1: error: specializing member ‘daal::services::interface1::Atomic<int>::Atomic’ requires ‘template<>’ syntax
 daal::services::Atomic<int>::Atomic() : _ptr(nullptr)
 ^

(repeated for each member function definition in that file)

**Comment by mascanio** [comment]
I'm having the same issue with the same compiler.

I've changed to tag 2017_u1 and is compiling now, might be a problem with #3 , as changing to 2017_u1 reverts that commit

**Comment by dr-pain** [comment]
Thank you guys for reports (you correctly identified root of cause). We reproduced problem and will provide fix soon.

**Comment by RuslanIsrafilov** [comment]
@yvdriess, the error should be fixed by d6a266c
