### ISSUE TITLE
Library files in /lnx32e as opposed to the standard /intel64_lin

### ISSUE THREAD

**Issue by steenax86** [01org/daal#7]
Resulting library files from building for `lnx32e` get put into `daal-daal_2017_beta_update1/__work/lnx32e/daal/lib/.` While building examples, `icc` looks for files in` intel64_lin`, the standard directory name for DAAL library files when bundled with Intel Parallel Studio. I fixed this mismatch on my build, but it maybe a good idea to standardize the location to intel64_lin across DAAL versions. Thank you.

**Comment by iburyl** [comment]
`__work` folder is a place where temproray files are located during the build. Final libraries are copied to  `__release_lnx` folder. They are located in standard folder: `__release_lnx/daal/lib/intel64_lin`
