### ISSUE TITLE
HOW-TO do asynchronous distributed training with Neural Net

### ISSUE THREAD

**Issue by fleapapa** [01org/daal#9]
Could anybody give an example of **asynchronous** version of neural_networks/neural_net_dense_distr.cpp? 

Thanks in advance!!

**Comment by Vika-F** [comment]
We provide code samples for the distributed algorithms available in Intel® DAAL.

To download the samples please go to [Intel® Software Product Samples and Tutorials](https://software.intel.com/en-us/product-code-samples) page. Then choose "Software Products" on the left and mark "Intel® Data Analytics Acceleration Library". You will see the download options.

Please download and unpack the appropriate archive.

You will find the asynchronous version of distributed neural networks training in this sample: daal/cpp/mpi/sources/neural_net_dense_asynch_distributed_mpi.cpp

Best regards,
Victoriya

**Comment by fleapapa** [comment]
Thanks a lot for the pointer!!
